wrangler，lark client and github action
idea2app/idea-lark-r2 pull request #1
Opened 2024-10-25 09:30 UTC by Soecka

[add] wrangler cli
[add] lark client
[add] github actions
[add] README

2024-11-07 20:55 UTC, TechQuery requested changes

2024-11-07 20:55 UTC, TechQuery commented on .editorconfig
> +indent_style = tab
所有文件都用空格缩进嘛，不然在 GitHub 等一些网页上会显示特别长的缩进。

2024-11-07 20:55 UTC, TechQuery commented on .github/workflows/main.yml
> +        uses: cloudflare/wrangler-action@v3
```suggestion
      - name: Deploy to CloudFlare
        uses: cloudflare/wrangler-action@v3
```

2024-11-07 20:55 UTC, TechQuery commented on .github/workflows/main.yml
> +      - name: print deployment-url
```suggestion
      - name: Print Deployment URL
```

2024-11-07 20:55 UTC, TechQuery commented on .github/workflows/main.yml
> +        run: echo $DEPLOYMENT_URL
```suggestion
        run: echo ${DEPLOYMENT_URL}
```

2024-11-07 20:55 UTC, TechQuery commented on .github/workflows/replace-repository-name.sh
> +    $(grep -i $SourceName -rl . --exclude-dir=.git --exclude-dir=node_modules)
多加一行：https://github.com/idea2app/Next-Bootstrap-ts/blob/dcd55f10ec0088562c939bf0fc3cd8d23aff807e/.github/workflows/replace-repository-name.sh#L9

2024-11-07 20:55 UTC, TechQuery commented on .gitignore
> +\*.pid.lock
```suggestion
*.pid.lock
```

2024-11-07 20:55 UTC, TechQuery commented on .gitignore
> +.rts2_cache_umd/
```suggestion
.rts2_cache_*/
```

2024-11-07 20:55 UTC, TechQuery commented on .gitignore
> +.env.local
```suggestion
.env*.local
```

2024-11-07 20:55 UTC, TechQuery commented on .gitignore
> +# parcel-bundler cache (https://parceljs.org/)
```suggestion
# Parcel bundler cache (https://parceljs.org/)
```

2024-11-07 20:55 UTC, TechQuery commented on .gitignore
> +.yarn/install-state.gz
```suggestion
.yarn/*
```

2024-11-07 20:55 UTC, TechQuery commented on README.md
> +This Cloudflare worker uploads images synchronously from lark base to R2 object storage. To utilize this functionality, you need to set up a lark base workflow which sends an HTTP request to the work
```suggestion
This CloudFlare worker uploads images synchronously from Lark base to R2 object storage. To utilize this functionality, you need to set up a Lark base workflow which sends an HTTP request to the worker. Subsequently, the worker retrieves the image from Lark and transfers it to R2.
```

2024-11-07 20:55 UTC, TechQuery commented on README.md
> +[![CI & CD](https://github.com/idea2app/React-MobX-Bootstrap-ts/actions/workflows/main.yml/badge.svg)][1] [![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)][2] [![Open in Gitpod]
```suggestion
[![CI & CD](https://github.com/idea2app/idea2app-lark-r2/actions/workflows/main.yml/badge.svg)][1]
[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)][2]
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)][3]
[![Deploy to Cloudflare Workers](https://deploy.workers.cloudflare.com/button)][4]
```

2024-11-07 20:55 UTC, TechQuery commented on README.md
> +# idea2app-lark-R2
```suggestion
# idea2app-Lark-R2
```

2024-11-07 20:55 UTC, TechQuery commented on README.md
> +### Github Action config
```suggestion
### GitHub actions configuration
```

2024-11-07 20:55 UTC, TechQuery commented on README.md
> +Set GitHub action variables properly to automatically deploy after every push
```suggestion
Set GitHub action variables properly to automatically deploy after every pushing.
```

2024-11-07 20:55 UTC, TechQuery commented on README.md
> +# your bucket base url, which you can set later with custom domains
```suggestion
# your Bucket base URL, which you can set later with custom domains
```

2024-11-07 20:55 UTC, TechQuery commented on README.md
> +[3]: https://gitpod.io/?autostart=true#https://github.com/idea2app/React-MobX-Bootstrap-ts
仓库名都没改

2024-11-07 20:55 UTC, TechQuery commented on .github/workflows/main.yml
> +            deploy --minify src/index.tsx
```suggestion
            deploy --minify src/index.ts
```

2024-11-07 20:55 UTC, TechQuery commented on tsconfig.json
> +		"module": "es2022",
```suggestion
		"target": "ES2021",

		/* Specify a set of bundled library declaration files that describe the target runtime environment. */
		"lib": ["ES2021"],

		/* Specify what module code is generated. */
		"module": "ES2022",
```

2024-11-07 20:55 UTC, TechQuery commented on tsconfig.json
> +		"noEmit": true,
```suggestion
```

2024-11-07 20:55 UTC, TechQuery commented on src/lark.ts
> +	secret?: string;
```suggestion
	host = '';
	secret = '';
```

2024-11-07 20:55 UTC, TechQuery commented on src/lark.ts
> +			`${this.host}auth/v3/tenant_access_token/internal`,
```suggestion
			new URL(’auth/v3/tenant_access_token/internal`, this.host),
```

2024-11-07 20:55 UTC, TechQuery commented on src/index.ts
> +		for (const [key, value] of url.searchParams) searchParams[key] = value;
```suggestion
		const searchParams = Object.fromEntries([...url.searchParams]);
```

2024-11-07 20:55 UTC, TechQuery commented on src/index.ts
> +		larkClient.init({ id: LARK_ID, secret: LARK_SECRET, host: LARK_HOST });
既然用了打包器，那可以把这些环境变量放在 `.env` 文件中，让打包器在编译时写入，这样就不需要在每次请求的时候初始化了。

2024-11-07 20:55 UTC, TechQuery commented on src/index.ts
> +				const key = `${file_token_array[index]}.${type_array[index].split('/')[1]}`;
```suggestion
				const key = `${file_token}.${type_array[index].split('/')[1]}`;
```

2024-11-07 20:55 UTC, TechQuery commented on src/index.ts
> +		await Promise.all(uploadPromises);
```suggestion
				return `${BUCKET_BASE_URL}/${key}`;
			}
		);

		const files = await Promise.all(uploadPromises);
```

2024-11-29 13:39 UTC, Soecka commented on .github/workflows/main.yml
> +        run: echo $DEPLOYMENT_URL
这个是为啥要套一层，不套也是能取到的

2024-11-29 13:44 UTC, TechQuery commented on .github/workflows/main.yml
> +        run: echo $DEPLOYMENT_URL
> 这个是为啥要套一层，不套也是能取到的

较长的变量名我习惯套一下会比较清晰，也与上面其它变量风格保持一致。

不过这也不是太大的问题，不改也行。

2024-11-29 13:47 UTC, Soecka commented on README.md
> +This Cloudflare worker uploads images synchronously from lark base to R2 object storage. To utilize this functionality, you need to set up a lark base workflow which sends an HTTP request to the work
Cloudflare 首字母大写就行了，F 没有大写，他们自己的开发者文档也是这样写的
https://developers.cloudflare.com/web3/ipfs-gateway/

2024-11-29 13:55 UTC, TechQuery commented on README.md
> +This Cloudflare worker uploads images synchronously from lark base to R2 object storage. To utilize this functionality, you need to set up a lark base workflow which sends an HTTP request to the work
> Cloudflare 首字母大写就行了，F 没有大写，他们自己的开发者文档也是这样写的
> https://developers.cloudflare.com/web3/ipfs-gateway/

好的，遵照官方商标指南：https://www.cloudflare-cn.com/trademark/

2024-11-29 14:52 UTC, Soecka commented on src/index.ts
> +		larkClient.init({ id: LARK_ID, secret: LARK_SECRET, host: LARK_HOST });
只能从 fetch 的参数 env 里面取，这不是一个可以从 process.env 取的全局变量

我加了个判断

2024-11-29 15:24 UTC, TechQuery requested changes

2024-11-29 15:24 UTC, TechQuery commented on .github/workflows/replace-repository-name.sh
> -    $(grep -i $SourceOwner/$SourceName -rl . --exclude-dir=.git --exclude-dir=node_modules)
排除目录的参数应该保留吧？

2024-11-29 15:24 UTC, TechQuery commented on .gitignore
> +.pnp.\*
```suggestion
.pnp.*
```

2024-11-29 15:24 UTC, TechQuery commented on src/index.ts
> +    async fetch(request, env): Promise<Response> {
可以如下改写来减少缩进：
```ts
async function fetch() {
}

export default { fetch };
```

2024-11-29 15:24 UTC, TechQuery commented on src/lark.ts
>  }
改为 `type` + `Record`

2024-11-29 15:24 UTC, TechQuery commented on tsconfig.json
> +        "skipLibCheck": true
```suggestion
        "module": "ES2022",
        "moduleResolution": "Bundler",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "allowSyntheticDefaultImports": true,
        "forceConsistentCasingInFileNames": true,
        "strict": true,
        "skipLibCheck": true,
        "types": ["@cloudflare/workers-types/2023-07-01"],
```
前面都是与模块机制强相关的选项，第三方库的放最后。

2024-11-29 15:24 UTC, TechQuery commented on tsconfig.json
> +    "include": ["worker-configuration.d.ts", "src/**/*.ts"]
```suggestion
    "include": ["worker-configuration.d.ts", "src/**/*.ts"]
```
两者没有交集，可以省略 `exclude`。

2024-11-29 15:48 UTC, Soecka commented on .github/workflows/replace-repository-name.sh
> -    $(grep -i $SourceOwner/$SourceName -rl . --exclude-dir=.git --exclude-dir=node_modules)
我照抄的你在 next 仓库写的版本，通过模板创建仓库的时候这些文件应该都没有

2024-11-29 16:08 UTC, Soecka commented on .github/workflows/replace-repository-name.sh
> -    $(grep -i $SourceOwner/$SourceName -rl . --exclude-dir=.git --exclude-dir=node_modules)
另外 template 创建事件我找到了另外一个方法

```yml
name: Setup repository

on:
  create

jobs:
  create_issue:
    if: github.event.ref == github.event.master_branch
```

2024-11-29 18:07 UTC, TechQuery commented on .github/workflows/replace-repository-name.sh
> -    $(grep -i $SourceOwner/$SourceName -rl . --exclude-dir=.git --exclude-dir=node_modules)
> 我照抄的你在 next 仓库写的版本，通过模板创建仓库的时候这些文件应该都没有

我刚更新，主要是在本地运行不排除会很卡：https://github.com/idea2app/Next-Bootstrap-ts/commit/f181e414e4223230cee5aad401fab3e0d814ca30

2024-12-03 13:16 UTC, TechQuery approved these changes

2024-12-03 13:17 UTC, merged